/* Generated by automated build script */
#define RELEASE 0.65
#define TEXTVER "Based on Putty 0.65 2015-19-19, WinCrypt &&\n patches of Markus Braeunig and Christopher Racky"
#define SSHVER "PuTTYCert-Release-0.65 2015-19-19"
#define BINARY_VERSION 0,65,0,0