/* Generated by automated build script */
#define RELEASE 0.66
#define TEXTVER "Based on Putty 0.66 2015-11-24, WinCrypt &&\n patches of Markus Braeunig and Christopher Racky"
#define SSHVER "PuTTYCert-Release-0.66 2015-11-24"
#define BINARY_VERSION 0,66,0,0
